//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHospitalMCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public int idCita { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public Nullable<int> idMedico { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
